const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Extracted directly from the standalone SensorModel product's real
// sensor definitions (public/sensormodel.html) — 71 pre-built sensor
// configurations across 18 industry verticals, each with realistic
// baseline/warn/critical thresholds and typical remaining-useful-life
// data. This is what CorverxisLab data sources can now start from
// instead of a blank configuration.
const CATALOG_ENTRIES = [
  {
    "vertical": "Manufacturing",
    "sensorKey": "mfg_vib",
    "name": "CNC Spindle Vibration",
    "unit": "mm/s",
    "baselineValue": 1.2,
    "warnThreshold": 4.2,
    "critThreshold": 8.5,
    "ruLHoursAtCrit": 2400,
    "colorHex": "#00c2e0",
    "freqCategory": "bearing",
    "description": "5-axis CNC machining center"
  },
  {
    "vertical": "Manufacturing",
    "sensorKey": "mfg_temp",
    "name": "Spindle Bearing Temp",
    "unit": "degC",
    "baselineValue": 42.0,
    "warnThreshold": 65.0,
    "critThreshold": 85.0,
    "ruLHoursAtCrit": 3200,
    "colorHex": "#f59e0b",
    "freqCategory": "thermal",
    "description": "Ball bearing inner race"
  },
  {
    "vertical": "Manufacturing",
    "sensorKey": "mfg_curr",
    "name": "Motor Drive Current",
    "unit": "A",
    "baselineValue": 18.0,
    "warnThreshold": 28.0,
    "critThreshold": 38.0,
    "ruLHoursAtCrit": 5000,
    "colorHex": "#22c55e",
    "freqCategory": "current",
    "description": "3-phase induction motor"
  },
  {
    "vertical": "Manufacturing",
    "sensorKey": "mfg_press",
    "name": "Hydraulic System Pressure",
    "unit": "bar",
    "baselineValue": 120.0,
    "warnThreshold": 145.0,
    "critThreshold": 160.0,
    "ruLHoursAtCrit": 4200,
    "colorHex": "#8b5cf6",
    "freqCategory": "pressure",
    "description": "Hydraulic clamping unit"
  },
  {
    "vertical": "Industrial Automation",
    "sensorKey": "aut_servo",
    "name": "Servo Motor Torque",
    "unit": "Nm",
    "baselineValue": 45.0,
    "warnThreshold": 78.0,
    "critThreshold": 95.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#00c2e0",
    "freqCategory": "torque",
    "description": "6-axis robot joint 1"
  },
  {
    "vertical": "Industrial Automation",
    "sensorKey": "aut_flow",
    "name": "Process Flow Rate",
    "unit": "L/min",
    "baselineValue": 85.0,
    "warnThreshold": 62.0,
    "critThreshold": 45.0,
    "ruLHoursAtCrit": 6500,
    "colorHex": "#f59e0b",
    "freqCategory": "flow",
    "description": "Coolant circulation pump"
  },
  {
    "vertical": "Industrial Automation",
    "sensorKey": "aut_pos",
    "name": "Linear Position Encoder",
    "unit": "um",
    "baselineValue": 0.5,
    "warnThreshold": 8.0,
    "critThreshold": 25.0,
    "ruLHoursAtCrit": 12000,
    "colorHex": "#22c55e",
    "freqCategory": "position",
    "description": "Ball screw assembly"
  },
  {
    "vertical": "Industrial Automation",
    "sensorKey": "aut_ae",
    "name": "Acoustic Emission",
    "unit": "dBV",
    "baselineValue": 52.0,
    "warnThreshold": 72.0,
    "critThreshold": 88.0,
    "ruLHoursAtCrit": 1800,
    "colorHex": "#8b5cf6",
    "freqCategory": "acoustic",
    "description": "Gear mesh monitoring"
  },
  {
    "vertical": "Healthcare",
    "sensorKey": "hth_ecg",
    "name": "ECG Heart Rate",
    "unit": "bpm",
    "baselineValue": 72.0,
    "warnThreshold": 100.0,
    "critThreshold": 130.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#ef4444",
    "freqCategory": "cardiac",
    "description": "Lead II continuous monitoring"
  },
  {
    "vertical": "Healthcare",
    "sensorKey": "hth_spo2",
    "name": "SpO2 Oxygen Saturation",
    "unit": "%",
    "baselineValue": 98.0,
    "warnThreshold": 94.0,
    "critThreshold": 90.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#00c2e0",
    "freqCategory": "oxygen",
    "description": "Pulse oximetry sensor"
  },
  {
    "vertical": "Healthcare",
    "sensorKey": "hth_bp",
    "name": "Blood Pressure (systolic)",
    "unit": "mmHg",
    "baselineValue": 120.0,
    "warnThreshold": 140.0,
    "critThreshold": 180.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#f59e0b",
    "freqCategory": "pressure",
    "description": "Continuous NIBP cuff"
  },
  {
    "vertical": "Healthcare",
    "sensorKey": "hth_temp",
    "name": "Patient Body Temperature",
    "unit": "degC",
    "baselineValue": 36.8,
    "warnThreshold": 38.5,
    "critThreshold": 40.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#22c55e",
    "freqCategory": "thermal",
    "description": "Core temperature probe"
  },
  {
    "vertical": "Aerospace",
    "sensorKey": "aero_vib",
    "name": "Engine Fan Vibration",
    "unit": "g RMS",
    "baselineValue": 0.8,
    "warnThreshold": 2.5,
    "critThreshold": 5.0,
    "ruLHoursAtCrit": 25000,
    "colorHex": "#00c2e0",
    "freqCategory": "bearing",
    "description": "CFM56 fan blade tip"
  },
  {
    "vertical": "Aerospace",
    "sensorKey": "aero_temp",
    "name": "EGT Exhaust Gas Temp",
    "unit": "degC",
    "baselineValue": 620.0,
    "warnThreshold": 720.0,
    "critThreshold": 800.0,
    "ruLHoursAtCrit": 18000,
    "colorHex": "#ef4444",
    "freqCategory": "thermal",
    "description": "Turbine exit temperature"
  },
  {
    "vertical": "Aerospace",
    "sensorKey": "aero_press",
    "name": "Hydraulic System Pressure",
    "unit": "psi",
    "baselineValue": 3000.0,
    "warnThreshold": 3200.0,
    "critThreshold": 3400.0,
    "ruLHoursAtCrit": 22000,
    "colorHex": "#8b5cf6",
    "freqCategory": "pressure",
    "description": "Primary flight control"
  },
  {
    "vertical": "Aerospace",
    "sensorKey": "aero_oil",
    "name": "Engine Oil Pressure",
    "unit": "psi",
    "baselineValue": 60.0,
    "warnThreshold": 45.0,
    "critThreshold": 35.0,
    "ruLHoursAtCrit": 15000,
    "colorHex": "#f59e0b",
    "freqCategory": "pressure",
    "description": "Main oil gallery"
  },
  {
    "vertical": "EV Battery",
    "sensorKey": "ev_temp",
    "name": "Cell Temperature",
    "unit": "degC",
    "baselineValue": 28.0,
    "warnThreshold": 45.0,
    "critThreshold": 60.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#ef4444",
    "freqCategory": "thermal",
    "description": "NMC 21700 module center"
  },
  {
    "vertical": "EV Battery",
    "sensorKey": "ev_volt",
    "name": "Cell Voltage",
    "unit": "V",
    "baselineValue": 3.7,
    "warnThreshold": 4.18,
    "critThreshold": 4.25,
    "ruLHoursAtCrit": 9500,
    "colorHex": "#00c2e0",
    "freqCategory": "voltage",
    "description": "Cell block monitor IC"
  },
  {
    "vertical": "EV Battery",
    "sensorKey": "ev_curr",
    "name": "Pack Charge Current",
    "unit": "A",
    "baselineValue": 45.0,
    "warnThreshold": 120.0,
    "critThreshold": 180.0,
    "ruLHoursAtCrit": 7200,
    "colorHex": "#22c55e",
    "freqCategory": "current",
    "description": "BMS Hall effect sensor"
  },
  {
    "vertical": "EV Battery",
    "sensorKey": "ev_soc",
    "name": "State of Charge",
    "unit": "%",
    "baselineValue": 75.0,
    "warnThreshold": 15.0,
    "critThreshold": 8.0,
    "ruLHoursAtCrit": 10000,
    "colorHex": "#8b5cf6",
    "freqCategory": "soc",
    "description": "EKF SOC estimator"
  },
  {
    "vertical": "Power Systems",
    "sensorKey": "pwr_curr",
    "name": "Transformer Current",
    "unit": "A",
    "baselineValue": 420.0,
    "warnThreshold": 520.0,
    "critThreshold": 600.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "current",
    "description": "11kV/415V distribution TX"
  },
  {
    "vertical": "Power Systems",
    "sensorKey": "pwr_temp",
    "name": "Transformer Oil Temp",
    "unit": "degC",
    "baselineValue": 55.0,
    "warnThreshold": 80.0,
    "critThreshold": 95.0,
    "ruLHoursAtCrit": 50000,
    "colorHex": "#f59e0b",
    "freqCategory": "thermal",
    "description": "Winding hot-spot sensor"
  },
  {
    "vertical": "Power Systems",
    "sensorKey": "pwr_pdis",
    "name": "Partial Discharge",
    "unit": "pC",
    "baselineValue": 15.0,
    "warnThreshold": 100.0,
    "critThreshold": 500.0,
    "ruLHoursAtCrit": 15000,
    "colorHex": "#ef4444",
    "freqCategory": "acoustic",
    "description": "HV cable insulation"
  },
  {
    "vertical": "Power Systems",
    "sensorKey": "pwr_freq",
    "name": "Grid Frequency",
    "unit": "Hz",
    "baselineValue": 50.0,
    "warnThreshold": 49.8,
    "critThreshold": 49.5,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#22c55e",
    "freqCategory": "frequency",
    "description": "Grid synchronisation"
  },
  {
    "vertical": "Mining",
    "sensorKey": "min_vib",
    "name": "Crusher Bearing Vibration",
    "unit": "mm/s",
    "baselineValue": 2.8,
    "warnThreshold": 8.5,
    "critThreshold": 18.0,
    "ruLHoursAtCrit": 1200,
    "colorHex": "#00c2e0",
    "freqCategory": "bearing",
    "description": "Primary jaw crusher"
  },
  {
    "vertical": "Mining",
    "sensorKey": "min_dust",
    "name": "Respirable Dust (PM2.5)",
    "unit": "mg/m3",
    "baselineValue": 0.8,
    "warnThreshold": 2.0,
    "critThreshold": 3.5,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#f59e0b",
    "freqCategory": "chemical",
    "description": "Underground level 3"
  },
  {
    "vertical": "Mining",
    "sensorKey": "min_gas",
    "name": "Methane Concentration",
    "unit": "% LEL",
    "baselineValue": 2.0,
    "warnThreshold": 20.0,
    "critThreshold": 40.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#ef4444",
    "freqCategory": "chemical",
    "description": "CH4 sensor array"
  },
  {
    "vertical": "Mining",
    "sensorKey": "min_stress",
    "name": "Roof Support Load",
    "unit": "t",
    "baselineValue": 45.0,
    "warnThreshold": 72.0,
    "critThreshold": 90.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#22c55e",
    "freqCategory": "pressure",
    "description": "Hydraulic prop gauge"
  },
  {
    "vertical": "Renewable Energy",
    "sensorKey": "re_vib",
    "name": "Wind Turbine Gearbox Vib",
    "unit": "mm/s",
    "baselineValue": 3.5,
    "warnThreshold": 9.0,
    "critThreshold": 18.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#00c2e0",
    "freqCategory": "bearing",
    "description": "Main gearbox HSS"
  },
  {
    "vertical": "Renewable Energy",
    "sensorKey": "re_temp",
    "name": "Nacelle Ambient Temp",
    "unit": "degC",
    "baselineValue": 35.0,
    "warnThreshold": 60.0,
    "critThreshold": 75.0,
    "ruLHoursAtCrit": 35000,
    "colorHex": "#f59e0b",
    "freqCategory": "thermal",
    "description": "Internal nacelle"
  },
  {
    "vertical": "Renewable Energy",
    "sensorKey": "re_power",
    "name": "Active Power Output",
    "unit": "kW",
    "baselineValue": 1850.0,
    "warnThreshold": 600.0,
    "critThreshold": 200.0,
    "ruLHoursAtCrit": 999999,
    "colorHex": "#22c55e",
    "freqCategory": "power",
    "description": "15MW offshore turbine"
  },
  {
    "vertical": "Renewable Energy",
    "sensorKey": "re_pv",
    "name": "PV Panel Temperature",
    "unit": "degC",
    "baselineValue": 45.0,
    "warnThreshold": 70.0,
    "critThreshold": 85.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#8b5cf6",
    "freqCategory": "thermal",
    "description": "Bifacial PV module"
  },
  {
    "vertical": "LVDT \u2014 Linear Displacement",
    "sensorKey": "lvdt_main",
    "name": "LVDT Primary Bore Depth",
    "unit": "mm",
    "baselineValue": 24.0,
    "warnThreshold": 0.05,
    "critThreshold": 0.12,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "position",
    "description": "Linear Variable Differential Transformer \u2014 bore depth on engine block. Resolution 0.1\u00b5m. Range \u00b125mm. Carrier freq 5kHz."
  },
  {
    "vertical": "LVDT \u2014 Linear Displacement",
    "sensorKey": "lvdt_gap",
    "name": "LVDT Air Gap Measurement",
    "unit": "mm",
    "baselineValue": 2.5,
    "warnThreshold": 0.03,
    "critThreshold": 0.08,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "position",
    "description": "LVDT gap sensor on valve seat. Monitors seating depth in cylinder head. Tolerance \u00b10.03mm."
  },
  {
    "vertical": "LVDT \u2014 Linear Displacement",
    "sensorKey": "lvdt_stroke",
    "name": "LVDT Actuator Stroke",
    "unit": "mm",
    "baselineValue": 100.0,
    "warnThreshold": 0.2,
    "critThreshold": 0.5,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#8b5cf6",
    "freqCategory": "position",
    "description": "LVDT on hydraulic actuator stroke. End-of-travel detection. Range 0-150mm. IP67 rated."
  },
  {
    "vertical": "LVDT \u2014 Linear Displacement",
    "sensorKey": "lvdt_taper",
    "name": "LVDT Taper Gauge",
    "unit": "\u00b5m",
    "baselineValue": 0.0,
    "warnThreshold": 15.0,
    "critThreshold": 30.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#f59e0b",
    "freqCategory": "position",
    "description": "LVDT differential taper measurement on crankshaft journal. Detects out-of-round up to 0.001mm."
  },
  {
    "vertical": "Laser Micrometers",
    "sensorKey": "lmm_od",
    "name": "Laser Micrometer \u2014 Shaft OD",
    "unit": "mm",
    "baselineValue": 48.0,
    "warnThreshold": 0.02,
    "critThreshold": 0.05,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#ef4444",
    "freqCategory": "optical",
    "description": "Non-contact laser micrometer on rotating shaft OD. Keyence LS-9000. Scan rate 2400/sec. Resolution 0.01\u00b5m."
  },
  {
    "vertical": "Laser Micrometers",
    "sensorKey": "lmm_wire",
    "name": "Laser Wire Gauge",
    "unit": "mm",
    "baselineValue": 1.25,
    "warnThreshold": 0.01,
    "critThreshold": 0.025,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#ef4444",
    "freqCategory": "optical",
    "description": "Laser micrometer for wire diameter in cable harness production. \u00b10.001mm accuracy. In-line 100% inspection."
  },
  {
    "vertical": "Laser Micrometers",
    "sensorKey": "lmm_thread",
    "name": "Laser Thread Profile",
    "unit": "\u00b5m",
    "baselineValue": 0.0,
    "warnThreshold": 10.0,
    "critThreshold": 25.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "optical",
    "description": "Laser thread profile scanner on M10 bolts. Measures pitch diameter, lead, and flank angle simultaneously."
  },
  {
    "vertical": "Laser Micrometers",
    "sensorKey": "lmm_flatness",
    "name": "Laser Flatness Scanner",
    "unit": "\u00b5m",
    "baselineValue": 0.0,
    "warnThreshold": 5.0,
    "critThreshold": 15.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#22c55e",
    "freqCategory": "optical",
    "description": "Multi-point laser flatness scan on sealing surfaces. 16-point matrix. Detects warpage and taper."
  },
  {
    "vertical": "Proximity Sensors",
    "sensorKey": "prox_induct",
    "name": "Inductive Proximity \u2014 Part Present",
    "unit": "bool",
    "baselineValue": 1.0,
    "warnThreshold": 0.5,
    "critThreshold": 0.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#22c55e",
    "freqCategory": "proximity",
    "description": "Inductive proximity sensor for metallic part presence detection. Sensing range 8mm. Response time 0.1ms. Poka-yoke on assembly station."
  },
  {
    "vertical": "Proximity Sensors",
    "sensorKey": "prox_cap",
    "name": "Capacitive Proximity \u2014 Level",
    "unit": "%",
    "baselineValue": 75.0,
    "warnThreshold": 20.0,
    "critThreshold": 10.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#f59e0b",
    "freqCategory": "proximity",
    "description": "Capacitive proximity sensor for coolant level in CNC reservoir. Detects metallic and non-metallic media. IP68."
  },
  {
    "vertical": "Proximity Sensors",
    "sensorKey": "prox_ultras",
    "name": "Ultrasonic Proximity \u2014 Conveyor",
    "unit": "mm",
    "baselineValue": 250.0,
    "warnThreshold": 50.0,
    "critThreshold": 20.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "proximity",
    "description": "Ultrasonic proximity on conveyor gap detection. Range 20-350mm. Not affected by colour, surface finish, or lighting."
  },
  {
    "vertical": "Proximity Sensors",
    "sensorKey": "prox_mag",
    "name": "Magnetic Proximity \u2014 Cylinder Pos",
    "unit": "bool",
    "baselineValue": 1.0,
    "warnThreshold": 0.5,
    "critThreshold": 0.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#8b5cf6",
    "freqCategory": "proximity",
    "description": "Magnetic proximity on pneumatic cylinder rod magnet. T-slot mount. Detects end-of-stroke position without contact."
  },
  {
    "vertical": "Force & Torque Sensors",
    "sensorKey": "ft_press_force",
    "name": "Press Force \u2014 Bearing Insert",
    "unit": "kN",
    "baselineValue": 42.0,
    "warnThreshold": 48.0,
    "critThreshold": 55.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#ef4444",
    "freqCategory": "force",
    "description": "Load cell on bearing press-fit station. Monitors insertion force profile. Peak force 50kN. Detects mis-aligned or undersized bearings."
  },
  {
    "vertical": "Force & Torque Sensors",
    "sensorKey": "ft_torque_run",
    "name": "Torque \u2014 Assembly Nutrunner",
    "unit": "Nm",
    "baselineValue": 65.0,
    "warnThreshold": 3.0,
    "critThreshold": 6.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#f59e0b",
    "freqCategory": "torque",
    "description": "Inline torque transducer on DC nutrunner. Safety-critical fasteners. Target 65Nm \u00b15%. Result stored in MES per joint per VIN."
  },
  {
    "vertical": "Force & Torque Sensors",
    "sensorKey": "ft_grip",
    "name": "Gripper Force \u2014 Robot Arm",
    "unit": "N",
    "baselineValue": 120.0,
    "warnThreshold": 20.0,
    "critThreshold": 40.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "force",
    "description": "6-axis force/torque sensor on robot end effector. ATI Mini45. Detects incorrect part pickup, collision, and slip."
  },
  {
    "vertical": "Force & Torque Sensors",
    "sensorKey": "ft_cut",
    "name": "Cutting Force \u2014 CNC Spindle",
    "unit": "N",
    "baselineValue": 800.0,
    "warnThreshold": 300.0,
    "critThreshold": 600.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#8b5cf6",
    "freqCategory": "force",
    "description": "Piezoelectric dynamometer under CNC fixture. Monitors Fx/Fy/Fz cutting forces. Tool wear detection via force trend analysis."
  },
  {
    "vertical": "Vision & Optical Sensors",
    "sensorKey": "vis_defect",
    "name": "Vision AI \u2014 Surface Defect Rate",
    "unit": "%",
    "baselineValue": 0.5,
    "warnThreshold": 2.0,
    "critThreshold": 5.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "optical",
    "description": "Corverxis Vision AI defect detection camera. 2448\u00d72048 resolution. CNN model. Detects scratches, voids, porosity, and dimensional OOT in real time."
  },
  {
    "vertical": "Vision & Optical Sensors",
    "sensorKey": "vis_color",
    "name": "Vision \u2014 Color Verification",
    "unit": "dE",
    "baselineValue": 0.8,
    "warnThreshold": 2.0,
    "critThreshold": 4.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#22c55e",
    "freqCategory": "optical",
    "description": "Machine vision color verify sensor on painted parts. Delta-E colour difference measurement. Rejects incorrect colour codes before assembly."
  },
  {
    "vertical": "Vision & Optical Sensors",
    "sensorKey": "vis_barcode",
    "name": "Vision \u2014 Barcode Decode Rate",
    "unit": "%",
    "baselineValue": 99.8,
    "warnThreshold": 98.0,
    "critThreshold": 95.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#f59e0b",
    "freqCategory": "optical",
    "description": "1D/2D barcode reader on end-of-line traceability station. Reads DataMatrix, QR, Code128. Linked to MES WO and serial number."
  },
  {
    "vertical": "Vision & Optical Sensors",
    "sensorKey": "vis_fov",
    "name": "Vision \u2014 Laser Profilometer",
    "unit": "\u00b5m",
    "baselineValue": 0.0,
    "warnThreshold": 50.0,
    "critThreshold": 100.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#8b5cf6",
    "freqCategory": "optical",
    "description": "3D laser line profilometer for weld bead profile. Measures bead width, height, and undercut. 3200 points/profile at 4kHz."
  },
  {
    "vertical": "Hall Effect Sensors",
    "sensorKey": "hall_rpm",
    "name": "Hall Effect \u2014 Motor RPM",
    "unit": "RPM",
    "baselineValue": 1450.0,
    "warnThreshold": 200.0,
    "critThreshold": 400.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#22c55e",
    "freqCategory": "magnetic",
    "description": "Hall effect speed sensor on 3-phase motor shaft. Gear tooth detection. Resolution 1 pulse per tooth. 60-tooth ring. Used for closed-loop speed control."
  },
  {
    "vertical": "Hall Effect Sensors",
    "sensorKey": "hall_pos",
    "name": "Hall Effect \u2014 Linear Position",
    "unit": "mm",
    "baselineValue": 50.0,
    "warnThreshold": 5.0,
    "critThreshold": 10.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "magnetic",
    "description": "Linear Hall effect position sensor on EV battery pack lid. Detects lid open/closed state and intermediate positions. Contactless. 0-100mm range."
  },
  {
    "vertical": "Hall Effect Sensors",
    "sensorKey": "hall_current",
    "name": "Hall Effect \u2014 Bus Current",
    "unit": "A",
    "baselineValue": 85.0,
    "warnThreshold": 140.0,
    "critThreshold": 180.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#ef4444",
    "freqCategory": "magnetic",
    "description": "Hall effect current sensor on DC bus bar. Non-invasive, no shunt resistor. \u00b1300A range. Used for EV inverter current monitoring."
  },
  {
    "vertical": "Hall Effect Sensors",
    "sensorKey": "hall_brake",
    "name": "Hall Effect \u2014 Brake Pad Wear",
    "unit": "mm",
    "baselineValue": 10.0,
    "warnThreshold": 4.0,
    "critThreshold": 2.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#f59e0b",
    "freqCategory": "magnetic",
    "description": "Hall effect brake pad wear sensor. Embedded magnet moves with pad. Distance to sensor correlates to remaining pad thickness. Safety critical."
  },
  {
    "vertical": "Pressure Sensor Housing",
    "sensorKey": "psh_hydro",
    "name": "Hydraulic Circuit Pressure",
    "unit": "bar",
    "baselineValue": 180.0,
    "warnThreshold": 220.0,
    "critThreshold": 250.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#8b5cf6",
    "freqCategory": "pressure",
    "description": "Stainless steel pressure sensor housing on hydraulic power pack. G1/4 process connection. 0-400 bar range. IEC 61010. 316L wetted parts."
  },
  {
    "vertical": "Pressure Sensor Housing",
    "sensorKey": "psh_coolant",
    "name": "Coolant System Pressure",
    "unit": "bar",
    "baselineValue": 3.2,
    "warnThreshold": 4.8,
    "critThreshold": 6.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "pressure",
    "description": "Sealed pressure sensor housing on CNC coolant circuit. Monitors pump health and filter blockage. Flush diaphragm. IP69K wash-down rated."
  },
  {
    "vertical": "Pressure Sensor Housing",
    "sensorKey": "psh_pneu",
    "name": "Pneumatic Supply Pressure",
    "unit": "bar",
    "baselineValue": 6.0,
    "warnThreshold": 1.0,
    "critThreshold": 2.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#22c55e",
    "freqCategory": "pressure",
    "description": "Pressure sensor on factory compressed air supply. Detects line pressure drop from leaks. 0-10 bar. DIN rail mounted transmitter housing."
  },
  {
    "vertical": "Temperature Sensor Components",
    "sensorKey": "tmp_tc_k",
    "name": "Type-K Thermocouple \u2014 Furnace",
    "unit": "\u00b0C",
    "baselineValue": 820.0,
    "warnThreshold": 50.0,
    "critThreshold": 100.0,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#ef4444",
    "freqCategory": "thermal",
    "description": "Type-K thermocouple junction in heat treatment furnace. Range 0-1250\u00b0C. Mineral insulated sheath. IEC 60584. \u00b11.5\u00b0C accuracy. 3-zone control."
  },
  {
    "vertical": "Temperature Sensor Components",
    "sensorKey": "tmp_rtd",
    "name": "PT100 RTD \u2014 Coolant Temp",
    "unit": "\u00b0C",
    "baselineValue": 42.0,
    "warnThreshold": 65.0,
    "critThreshold": 80.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#f59e0b",
    "freqCategory": "thermal",
    "description": "PT100 RTD sensor 4-wire connection. IEC 60751 Class A. \u00b10.15\u00b0C accuracy. CNC coolant monitoring. Stainless steel pocket. G1/4 thread."
  },
  {
    "vertical": "Temperature Sensor Components",
    "sensorKey": "tmp_ir",
    "name": "IR Thermometer \u2014 Weld Zone",
    "unit": "\u00b0C",
    "baselineValue": 680.0,
    "warnThreshold": 80.0,
    "critThreshold": 150.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "thermal",
    "description": "Infrared non-contact thermometer on MIG weld zone. Emissivity compensated for steel 0.85. Response time 1ms. 50:1 distance-to-spot ratio."
  },
  {
    "vertical": "Temperature Sensor Components",
    "sensorKey": "tmp_ntc",
    "name": "NTC Thermistor \u2014 PCB Temp",
    "unit": "\u00b0C",
    "baselineValue": 45.0,
    "warnThreshold": 75.0,
    "critThreshold": 95.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#22c55e",
    "freqCategory": "thermal",
    "description": "NTC 10k\u03a9 thermistor embedded in PCB hotspot. B-constant 3977K. 0.2\u00b0C resolution. Junction temperature monitoring on power electronics."
  },
  {
    "vertical": "Vibration Sensors",
    "sensorKey": "vib_accel",
    "name": "Piezoelectric Accelerometer",
    "unit": "g",
    "baselineValue": 0.8,
    "warnThreshold": 4.5,
    "critThreshold": 8.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#00c2e0",
    "freqCategory": "vibration",
    "description": "ICP piezoelectric accelerometer on gearbox housing. 100mV/g sensitivity. 0.5-10kHz bandwidth. Detects gear mesh frequency, bearing defects (BPFO/BPFI), and unbalance."
  },
  {
    "vertical": "Vibration Sensors",
    "sensorKey": "vib_mems",
    "name": "MEMS Accelerometer \u2014 Structural",
    "unit": "mg",
    "baselineValue": 2.0,
    "warnThreshold": 15.0,
    "critThreshold": 30.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#8b5cf6",
    "freqCategory": "vibration",
    "description": "MEMS triaxial accelerometer on press frame. 3-axis simultaneous. \u00b116g range. 1kHz ODR. Structural health monitoring. Detects looseness and resonance shifts."
  },
  {
    "vertical": "Vibration Sensors",
    "sensorKey": "vib_vel",
    "name": "Velocity Sensor \u2014 Pump Housing",
    "unit": "mm/s",
    "baselineValue": 2.5,
    "warnThreshold": 7.1,
    "critThreshold": 11.2,
    "ruLHoursAtCrit": 8760,
    "colorHex": "#f59e0b",
    "freqCategory": "vibration",
    "description": "Seismic velocity sensor on hydraulic pump housing. ISO 10816-3 Class II machine. 10Hz-1kHz. 4-20mA 2-wire transmitter. Weatherproof IP65."
  },
  {
    "vertical": "Vibration Sensors",
    "sensorKey": "vib_proxy",
    "name": "Eddy Current \u2014 Shaft Orbit",
    "unit": "\u00b5m",
    "baselineValue": 15.0,
    "warnThreshold": 80.0,
    "critThreshold": 150.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#ef4444",
    "freqCategory": "vibration",
    "description": "Eddy current displacement probe pair (X/Y) for shaft orbit measurement. API 670 compliant. 0-500\u00b5m range. 8mm probe. Detects oil whirl, rub, and misalignment."
  },
  {
    "vertical": "Current & Power Sensors",
    "sensorKey": "pwr_ct",
    "name": "Current Transformer \u2014 Motor",
    "unit": "A",
    "baselineValue": 42.0,
    "warnThreshold": 58.0,
    "critThreshold": 72.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#22c55e",
    "freqCategory": "electrical",
    "description": "Split-core current transformer on 3-phase motor feed. 100A:5A ratio. Clip-on, no downtime installation. Used for motor health monitoring and energy metering."
  },
  {
    "vertical": "Current & Power Sensors",
    "sensorKey": "pwr_watt",
    "name": "Power Meter \u2014 CNC Machine",
    "unit": "kW",
    "baselineValue": 18.5,
    "warnThreshold": 28.0,
    "critThreshold": 35.0,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#00c2e0",
    "freqCategory": "electrical",
    "description": "True RMS power meter on CNC machine supply. 3-phase 4-wire. Measures active, reactive, apparent power and power factor. Modbus RTU. Energy cost tracking."
  },
  {
    "vertical": "Current & Power Sensors",
    "sensorKey": "pwr_pf",
    "name": "Power Factor \u2014 Production Line",
    "unit": "pf",
    "baselineValue": 0.95,
    "warnThreshold": 0.12,
    "critThreshold": 0.2,
    "ruLHoursAtCrit": 87600,
    "colorHex": "#f59e0b",
    "freqCategory": "electrical",
    "description": "Power factor sensor on production line busbar. Poor PF below 0.85 incurs utility penalties. Detects capacitor bank failure and reactive load imbalance."
  },
  {
    "vertical": "Current & Power Sensors",
    "sensorKey": "pwr_leak",
    "name": "Earth Leakage Current",
    "unit": "mA",
    "baselineValue": 0.5,
    "warnThreshold": 10.0,
    "critThreshold": 30.0,
    "ruLHoursAtCrit": 43800,
    "colorHex": "#ef4444",
    "freqCategory": "electrical",
    "description": "Residual current monitor on equipment earth. IEC 60755. Detects insulation degradation before ground fault trip. Safety-critical monitoring. EN ISO 13849."
  }
];

async function seedCatalog(prismaClient) {
  const db = prismaClient || prisma;
  const existing = await db.sensorModelCatalogEntry.count();
  if (existing > 0) {
    console.log(`✓ SensorModel catalog already seeded (${existing} entries) — skipping`);
    return;
  }
  let created = 0;
  for (const entry of CATALOG_ENTRIES) {
    try {
      await db.sensorModelCatalogEntry.create({ data: entry });
      created++;
    } catch (e) {
      console.error(`⚠ Catalog entry seed failed for ${entry.sensorKey} (non-fatal):`, e.message);
    }
  }
  const verticals = [...new Set(CATALOG_ENTRIES.map(e => e.vertical))];
  console.log(`✓ SensorModel catalog: ${created} sensor definitions seeded across ${verticals.length} verticals`);
}

module.exports = { seedCatalog };

if (require.main === module) {
  seedCatalog()
    .catch((e) => { console.error('❌ Catalog seed failed:', e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
}
